# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove zelda_oot_mob.link.animation.idle.playing
tag @s remove zelda_oot_mob.link.animation.ocarina_idle.playing
tag @s remove zelda_oot_mob.link.animation.ocarina_playing_black.playing
tag @s remove zelda_oot_mob.link.animation.ocarina_playing_yellow.playing
tag @s remove zelda_oot_mob.link.animation.ocarina_playing_green.playing
tag @s remove zelda_oot_mob.link.animation.ocarina_playing_blue.playing
tag @s remove zelda_oot_mob.link.animation.ocarina_playing_red.playing