# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-0.9924f,-0.0872f,0.0868f,0f,-0.0747f,0.9877f,0.1376f,1.4375f,-0.0977f,0.13f,-0.9867f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,1.4375f,0f,0.0872f,-0.9962f,0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9141f,0.4053f,0.0105f,0.3125f,0.1617f,0.3882f,-0.9073f,1.3125f,-0.3718f,-0.8277f,-0.4204f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8608f,-0.491f,-0.1339f,-0.3125f,-0.0784f,0.3878f,-0.9184f,1.3125f,0.5028f,-0.7801f,-0.3723f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:twins/variants/default/apply