# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,1.05f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,1.05f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.05f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9763f,0f,-0.2164f,0.2188f,0f,1f,0f,0.9625f,0.2164f,0f,-0.9763f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9891f,0.0501f,-0.1383f,-0.2187f,0.0487f,0.9987f,0.0134f,0.9625f,0.1388f,0.0065f,-0.9903f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9891f,-0.0701f,-0.1298f,0.0831f,-0.0825f,0.9922f,0.0932f,0.525f,0.1222f,0.1029f,-0.9872f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9897f,0.067f,0.1268f,-0.0831f,0.0623f,0.9972f,-0.0407f,0.525f,-0.1291f,-0.0324f,-0.9911f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}