# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.05f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.05f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left_arm) { transformation: [-1f,0f,0f,0.2188f,0f,1f,0f,0.9625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_arm) { transformation: [-1f,0f,0f,-0.2187f,0f,1f,0f,0.9625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left_leg) { transformation: [-1f,0f,0f,0.0831f,0f,1f,0f,0.525f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_leg) { transformation: [-1f,0f,0f,-0.0831f,0f,1f,0f,0.525f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }