# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-1f,0f,0f,0f,0f,0.9042f,0.427f,1.2128f,0f,0.427f,-0.9042f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9042f,0.427f,1.2128f,0f,0.427f,-0.9042f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.2128f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.5613f,-0.1973f,0.8037f,0.2188f,-0.6463f,0.7112f,-0.2768f,1.1253f,-0.517f,-0.6748f,-0.5267f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8682f,0.1767f,-0.4637f,-0.2187f,0.3599f,0.8676f,-0.3433f,1.1253f,0.3416f,-0.4649f,-0.8168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9466f,-0.161f,-0.2794f,0.0831f,-0.2309f,0.9433f,0.2386f,0.7503f,0.2251f,0.2904f,-0.9301f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9537f,0.098f,0.2843f,-0.0831f,0.0393f,0.9779f,-0.2053f,0.7503f,-0.2981f,-0.1846f,-0.9365f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:kokiri_shopkeeper/variants/default/apply