# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-1f,0f,0f,0f,0f,0.9722f,0.2341f,1.0824f,0f,0.2341f,-0.9722f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9722f,0.2341f,1.0824f,0f,0.2341f,-0.9722f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0824f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8368f,0.0601f,0.5441f,0.2188f,-0.4983f,0.328f,-0.8026f,0.9949f,-0.2267f,-0.9428f,-0.2445f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9539f,0.0378f,-0.2978f,-0.2187f,0.285f,0.4257f,-0.8588f,0.9949f,0.0943f,-0.9041f,-0.4169f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9603f,-0.093f,-0.2628f,0.0831f,-0.142f,0.9744f,0.1742f,0.6199f,0.2399f,0.2046f,-0.949f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9537f,0.0717f,0.292f,-0.0831f,0.0393f,0.9925f,-0.1155f,0.6199f,-0.2981f,-0.0987f,-0.9494f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:kokiri_shopkeeper/variants/blink/apply