# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=zelda_oot.npc_model.fado.animation.idle.playing] run function zelda_oot:npc_model/fado/animations/idle/zzz/on_tick
execute on passengers run rotate @s ~ ~