# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,0.3625f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,0.3625f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9478f,-0.2651f,0.1773f,0.2188f,-0.1656f,0.8842f,0.4367f,0.275f,-0.2725f,0.3845f,-0.882f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7963f,0.3173f,-0.5149f,-0.2187f,0.0603f,0.8887f,0.4544f,0.275f,0.6019f,0.3308f,-0.7269f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9939f,-0.0889f,0.0645f,0.0831f,-0.0765f,0.1394f,-0.9873f,-0.1f,0.0788f,-0.9862f,-0.1454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9988f,0.0425f,-0.0262f,-0.0831f,0.0282f,0.0465f,-0.9985f,-0.1f,-0.0412f,-0.998f,-0.0476f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:know_it_all_brother/variants/default/apply