# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-0.9982f,0.0057f,-0.0593f,0f,0.0026f,0.9987f,0.0514f,0.3796f,0.0595f,0.0511f,-0.9969f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9982f,0.0057f,-0.0593f,0f,0.0026f,0.9987f,0.0514f,0.3796f,0.0595f,0.0511f,-0.9969f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3796f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9363f,-0.2567f,0.2397f,0.2188f,-0.1544f,0.9138f,0.3756f,0.275f,-0.3155f,0.3146f,-0.8953f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7515f,0.2999f,-0.5876f,-0.2187f,0.0351f,0.9076f,0.4183f,0.275f,0.6588f,0.2938f,-0.6926f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9939f,-0.0859f,0.0685f,0.0831f,-0.0765f,0.094f,-0.9926f,-0.1f,0.0788f,-0.9919f,-0.1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9988f,0.0433f,-0.0249f,-0.0831f,0.0282f,0.077f,-0.9966f,-0.1f,-0.0412f,-0.9961f,-0.0781f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:know_it_all_brother/variants/default/apply