# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:twins rig_hash set value '926453845a1b3f377b68e7b40b5caff7b1a1e1b9a0cd38cf69dd8460c7dc8486'
scoreboard objectives add aj.idle_stand.frame dummy
scoreboard objectives add aj.idle_stand2.frame dummy
scoreboard objectives add aj.idle_sit.frame dummy
scoreboard objectives add aj.idle_sit2.frame dummy