# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:twins rig_hash set value '28561adf3465a36fefa2e80c50a638bcac597e560a53f96e385d4ccd63dffb4e'
scoreboard objectives add aj.idle_stand.frame dummy
scoreboard objectives add aj.idle_stand2.frame dummy
scoreboard objectives add aj.idle_sit.frame dummy
scoreboard objectives add aj.idle_sit2.frame dummy