# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:twins rig_hash set value 'b3ff30aeabb7089291db0413edc7d1533da45896c600b806de05b86afa346ca1'
scoreboard objectives add aj.idle_stand.frame dummy
scoreboard objectives add aj.idle_stand2.frame dummy
scoreboard objectives add aj.idle_sit.frame dummy