# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot_mob:know_it_all_brother rig_hash set value '5a920c7647c774f552961476411945743f7d8bb930c81b472fa2e38afa05ff4e'
scoreboard objectives add aj.idle1.frame dummy
scoreboard objectives add aj.idle2.frame dummy
scoreboard objectives add aj.idle_sit1.frame dummy
scoreboard objectives add aj.idle_sit2.frame dummy
scoreboard objectives add aj.block.frame dummy
scoreboard objectives add aj.idle_rock.frame dummy
scoreboard objectives add aj.idle_grass.frame dummy
scoreboard objectives add aj.idle_attack.frame dummy