# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle1.frame
scoreboard objectives remove aj.idle2.frame
scoreboard objectives remove aj.idle_sit1.frame
scoreboard objectives remove aj.idle_sit2.frame
scoreboard objectives remove aj.block.frame
scoreboard objectives remove aj.idle_rock.frame
scoreboard objectives remove aj.idle_grass.frame
scoreboard objectives remove aj.idle_attack.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (zelda_oot_mob:know_it_all_brother)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'zelda_oot_mob:know_it_all_brother',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']