# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=zelda_oot.twins.animation.idle_stand.playing] run function zelda_oot:twins/animations/idle_stand/zzz/on_tick
execute if entity @s[tag=zelda_oot.twins.animation.idle_stand2.playing] run function zelda_oot:twins/animations/idle_stand2/zzz/on_tick
execute if entity @s[tag=zelda_oot.twins.animation.idle_sit.playing] run function zelda_oot:twins/animations/idle_sit/zzz/on_tick
execute if entity @s[tag=zelda_oot.twins.animation.idle_sit2.playing] run function zelda_oot:twins/animations/idle_sit2/zzz/on_tick
execute on passengers run rotate @s ~ ~