# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot_mob:fado rig_hash set value '553e14c7b74fa7baaf19fb16d7e7436d64595a3150ff38b7179a85ea64a9f27d'
scoreboard objectives add aj.idle.frame dummy