# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from storage animated_java:temp list[-1]
data remove storage animated_java:temp list[-1]
function animated_java:global/root/outdated_warning/loop/as_uuid with storage animated_java:temp args
execute store result score #length aj.i run data get storage animated_java:temp list
execute if score #length aj.i matches 1.. run function animated_java:global/root/outdated_warning/loop