# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot_mob:link rig_hash set value '21ae9c01ed4eb75093159c4d18fe5287c90974e16b60357052717a9c7198f372'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.ocarina_idle.frame dummy
scoreboard objectives add aj.ocarina_playing_black.frame dummy
scoreboard objectives add aj.ocarina_playing_yellow.frame dummy
scoreboard objectives add aj.ocarina_playing_green.frame dummy
scoreboard objectives add aj.ocarina_playing_blue.frame dummy
scoreboard objectives add aj.ocarina_playing_red.frame dummy