# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-0.9989f,-0.0045f,0.0474f,0f,-0.0021f,0.9987f,0.0514f,0.3796f,-0.0476f,0.0513f,-0.9976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9989f,-0.0045f,0.0474f,0f,-0.0021f,0.9987f,0.0514f,0.3796f,-0.0476f,0.0513f,-0.9976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3796f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.767f,0.5949f,0.2406f,0.2188f,0.0779f,0.4584f,-0.8853f,0.275f,-0.6369f,-0.6603f,-0.3979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8601f,-0.4805f,-0.1714f,-0.2187f,-0.119f,0.5157f,-0.8485f,0.275f,0.4961f,-0.7094f,-0.5007f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9939f,-0.0859f,0.0685f,0.0831f,-0.0765f,0.094f,-0.9926f,-0.1f,0.0788f,-0.9919f,-0.1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9988f,0.0433f,-0.0249f,-0.0831f,0.0282f,0.077f,-0.9966f,-0.1f,-0.0412f,-0.9961f,-0.0781f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:know_it_all_brother/variants/default/apply