# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "zelda_oot:fado"
data modify storage animated_java:temp entry.data.rig_hash set value "7e38a2c45e159c2b4eeb64a591281078e667a77ce0d9432f713c4075cad8c712"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=zelda_oot.fado.node.head] run function zelda_oot:fado/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=zelda_oot.fado.node.body] run function zelda_oot:fado/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=zelda_oot.fado.node.left_arm] run function zelda_oot:fado/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=zelda_oot.fado.node.right_arm] run function zelda_oot:fado/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=zelda_oot.fado.node.left_leg] run function zelda_oot:fado/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=zelda_oot.fado.node.right_leg] run function zelda_oot:fado/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function zelda_oot:fado/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function zelda_oot:fado/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function zelda_oot:fado/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new