# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,0.3625f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,0.3625f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.738f,0.6173f,0.2725f,0.2188f,0.094f,0.494f,-0.8644f,0.275f,-0.6682f,-0.6123f,-0.4226f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8601f,-0.4691f,-0.2004f,-0.2187f,-0.119f,0.5665f,-0.8154f,0.275f,0.4961f,-0.6775f,-0.5431f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9939f,-0.0889f,0.0645f,0.0831f,-0.0765f,0.1394f,-0.9873f,-0.1f,0.0788f,-0.9862f,-0.1454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9988f,0.0425f,-0.0262f,-0.0831f,0.0282f,0.0465f,-0.9985f,-0.1f,-0.0412f,-0.998f,-0.0476f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot_mob:know_it_all_brother/variants/default/apply