# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:fado rig_hash set value '7e38a2c45e159c2b4eeb64a591281078e667a77ce0d9432f713c4075cad8c712'
scoreboard objectives add aj.idle.frame dummy