# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:fado rig_hash set value 'c1489d71e3fd2e2120bd9e9e9918977a9f3dd802030cdb5d8a0e549081de8c41'
scoreboard objectives add aj.idle.frame dummy