# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:fado rig_hash set value '3ac93babca366c812bc05b2b98a5343df68604b44f5a74b3becdbcad01327c38'
scoreboard objectives add aj.idle.frame dummy