# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:npc_model/fado rig_hash set value 'f931726c36bc14f2411925faa62ee4dbb102ae842f80ac75af418a22c6d75438'
scoreboard objectives add aj.idle.frame dummy