# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function zelda_oot_mob:know_it_all_brother/animations/idle_rock/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1