# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=zelda_oot_mob.link.animation.idle.playing] run function zelda_oot_mob:link/animations/idle/zzz/on_tick
execute if entity @s[tag=zelda_oot_mob.link.animation.ocarina_idle.playing] run function zelda_oot_mob:link/animations/ocarina_idle/zzz/on_tick
execute if entity @s[tag=zelda_oot_mob.link.animation.ocarina_playing_black.playing] run function zelda_oot_mob:link/animations/ocarina_playing_black/zzz/on_tick
execute if entity @s[tag=zelda_oot_mob.link.animation.ocarina_playing_yellow.playing] run function zelda_oot_mob:link/animations/ocarina_playing_yellow/zzz/on_tick
execute if entity @s[tag=zelda_oot_mob.link.animation.ocarina_playing_green.playing] run function zelda_oot_mob:link/animations/ocarina_playing_green/zzz/on_tick
execute if entity @s[tag=zelda_oot_mob.link.animation.ocarina_playing_blue.playing] run function zelda_oot_mob:link/animations/ocarina_playing_blue/zzz/on_tick
execute if entity @s[tag=zelda_oot_mob.link.animation.ocarina_playing_red.playing] run function zelda_oot_mob:link/animations/ocarina_playing_red/zzz/on_tick
execute on passengers run rotate @s ~ ~