# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-0.9903f,0.1391f,-0.0037f,0f,0.138f,0.9849f,0.1045f,1f,0.0181f,0.1029f,-0.9945f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,0.9976f,0.0698f,1f,0f,0.0698f,-0.9976f,0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8935f,0.0486f,-0.4465f,0.2188f,0.3769f,-0.4595f,-0.8042f,0.9125f,-0.2443f,-0.8868f,0.3923f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8212f,-0.5655f,-0.0763f,-0.2187f,-0.2707f,0.5038f,-0.8203f,0.9125f,0.5023f,-0.653f,-0.5668f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:twins/variants/blink/apply