# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hat) {transformation: [-0.9989f,-0.0045f,0.0474f,0f,-0.0021f,0.9987f,0.0514f,1.0046f,-0.0476f,0.0513f,-0.9976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9989f,-0.0045f,0.0474f,0f,-0.0021f,0.9987f,0.0514f,1.0046f,-0.0476f,0.0513f,-0.9976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0046f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.767f,0.5949f,0.2406f,0.2188f,0.0779f,0.4584f,-0.8853f,0.9f,-0.6369f,-0.6603f,-0.3979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8601f,-0.4805f,-0.1714f,-0.2187f,-0.119f,0.5157f,-0.8485f,0.9f,0.4961f,-0.7094f,-0.5007f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9753f,-0.0531f,-0.2142f,0.0831f,-0.0791f,0.9903f,0.1144f,0.525f,0.2061f,0.1286f,-0.9701f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9697f,0.0573f,0.2376f,-0.0831f,0.0473f,0.9978f,-0.0473f,0.525f,-0.2397f,-0.0347f,-0.9702f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:know_it_all_brother/variants/default/apply