# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle1.playing] run function zelda_oot:know_it_all_brother/animations/idle1/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle2.playing] run function zelda_oot:know_it_all_brother/animations/idle2/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle_sit1.playing] run function zelda_oot:know_it_all_brother/animations/idle_sit1/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle_sit2.playing] run function zelda_oot:know_it_all_brother/animations/idle_sit2/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.block.playing] run function zelda_oot:know_it_all_brother/animations/block/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle_rock.playing] run function zelda_oot:know_it_all_brother/animations/idle_rock/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle_grass.playing] run function zelda_oot:know_it_all_brother/animations/idle_grass/zzz/on_tick
execute if entity @s[tag=zelda_oot.know_it_all_brother.animation.idle_attack.playing] run function zelda_oot:know_it_all_brother/animations/idle_attack/zzz/on_tick
execute on passengers run rotate @s ~ ~