# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:know_it_all_brother rig_hash set value '97619d7dfa1d9e27f9a269a9afbbfefc44be4eb3901e42ff01ca9f83e5eecbe2'
scoreboard objectives add aj.idle1.frame dummy
scoreboard objectives add aj.idle2.frame dummy
scoreboard objectives add aj.idle_sit1.frame dummy
scoreboard objectives add aj.idle_sit2.frame dummy
scoreboard objectives add aj.block.frame dummy
scoreboard objectives add aj.idle_rock.frame dummy
scoreboard objectives add aj.idle_grass.frame dummy
scoreboard objectives add aj.idle_attack.frame dummy