# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9972f,0.0747f,1.4435f,0f,0.0747f,-0.9972f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4435f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9694f,-0.2419f,-0.0423f,0.3125f,-0.2417f,0.9703f,-0.0106f,1.325f,0.0436f,0f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9824f,0.1721f,0.072f,-0.3125f,0.1812f,0.9721f,0.1488f,1.325f,-0.0444f,0.1592f,-0.9862f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9712f,-0.0486f,-0.2334f,0.1188f,-0.0782f,0.9898f,0.1194f,0.75f,0.2252f,0.1342f,-0.965f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9633f,0.0551f,0.2628f,-0.1187f,0.0438f,0.9979f,-0.0484f,0.75f,-0.2649f,-0.0351f,-0.9636f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot_mob:link/variants/blink/apply