# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,1.4375f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9537f,-0.3007f,0f,0.3125f,-0.3007f,0.9537f,0f,1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9728f,0.1925f,0.1285f,-0.3125f,0.2131f,0.9615f,0.1736f,1.3125f,-0.0902f,0.1963f,-0.9764f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.965f,-0.0421f,-0.2588f,0.1188f,-0.077f,0.989f,0.1261f,0.75f,0.2507f,0.1416f,-0.9577f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9537f,0.0522f,0.2961f,-0.1187f,0.0393f,0.998f,-0.0496f,0.75f,-0.2981f,-0.0356f,-0.9539f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:link/variants/default/apply