# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot_mob:twins rig_hash set value 'f224f400458ae8cf03e0da26a2f1cc4fb7da21b38481941a223820bafe85b105'
scoreboard objectives add aj.idle_stand.frame dummy
scoreboard objectives add aj.idle_stand2.frame dummy
scoreboard objectives add aj.idle_sit.frame dummy
scoreboard objectives add aj.idle_sit2.frame dummy