# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle_stand.frame
scoreboard objectives remove aj.idle_stand2.frame
scoreboard objectives remove aj.idle_sit.frame
scoreboard objectives remove aj.idle_sit2.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (zelda_oot_mob:twins)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'zelda_oot_mob:twins',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']