# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1.01f,0f,0f,0f,0f,0.9903f,0.1392f,1.45f,0f,0.1392f,-0.9903f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4435f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9544f,0.0817f,0.2872f,0.3125f,-0.2319f,0.4034f,-0.8851f,1.3125f,-0.1882f,-0.9114f,-0.3661f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9399f,-0.3387f,-0.0442f,-0.3125f,-0.0212f,0.1871f,-0.9821f,1.3125f,0.3409f,-0.9221f,-0.183f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ocarina) {transformation: [0.9914f,0.1305f,0f,-0.7719f,-0.113f,0.8586f,0.5f,1.2313f,0.0653f,-0.4957f,0.866f,0.3437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot_mob:link/variants/blink/apply