# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:link rig_hash set value 'e37732c44d01ac6b960deef2780d7dcc871db7805548ebcc0d45c2f015d98e6d'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.ocarina_idle.frame dummy
scoreboard objectives add aj.ocarina_playing_black.frame dummy
scoreboard objectives add aj.ocarina_playing_yellow.frame dummy
scoreboard objectives add aj.ocarina_playing_green.frame dummy
scoreboard objectives add aj.ocarina_playing_blue.frame dummy
scoreboard objectives add aj.ocarina_playing_red.frame dummy