# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:link rig_hash set value '57d49bd215f1f76facfcef906b1a67c0fd6f6064e3d595c346421bf3aa26221c'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.ocarina_idle.frame dummy
scoreboard objectives add aj.ocarina_playing_black.frame dummy
scoreboard objectives add aj.ocarina_playing_yellow.frame dummy
scoreboard objectives add aj.ocarina_playing_green.frame dummy
scoreboard objectives add aj.ocarina_playing_blue.frame dummy
scoreboard objectives add aj.ocarina_playing_red.frame dummy