# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:link rig_hash set value '2f505225a7cbfab391bea08f41609220cb1c93037e444e9c5ef2646a98290424'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.ocarina_idle.frame dummy
scoreboard objectives add aj.ocarina_playing_black.frame dummy
scoreboard objectives add aj.ocarina_playing_yellow.frame dummy
scoreboard objectives add aj.ocarina_playing_green.frame dummy
scoreboard objectives add aj.ocarina_playing_blue.frame dummy
scoreboard objectives add aj.ocarina_playing_red.frame dummy