# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.ocarina_idle.frame
scoreboard objectives remove aj.ocarina_playing_black.frame
scoreboard objectives remove aj.ocarina_playing_yellow.frame
scoreboard objectives remove aj.ocarina_playing_green.frame
scoreboard objectives remove aj.ocarina_playing_blue.frame
scoreboard objectives remove aj.ocarina_playing_red.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (zelda_oot:link)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'zelda_oot:link',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']