# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot_mob:kokiri_shopkeeper rig_hash set value '0ac0d64725c15dec45000e4dfa091a0575ecd19e90fc79ed4f9f89f3fbc226c3'
scoreboard objectives add aj.idle.frame dummy