# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage zelda_oot:kokiri_shopkeeper rig_hash set value 'c4abb2087ba6b418b7e16f161d4f731f3f6bc0f68b772ac550f495d0ace785dd'
scoreboard objectives add aj.idle.frame dummy