# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '0ac0d64725c15dec45000e4dfa091a0575ecd19e90fc79ed4f9f89f3fbc226c3'}}} run function animated_java:global/remove/outdated_rig
function zelda_oot_mob:kokiri_shopkeeper/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack