# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove zelda_oot.know_it_all_brother.animation.idle1.playing
tag @s remove zelda_oot.know_it_all_brother.animation.idle2.playing
tag @s remove zelda_oot.know_it_all_brother.animation.idle_sit1.playing
tag @s remove zelda_oot.know_it_all_brother.animation.idle_sit2.playing
tag @s remove zelda_oot.know_it_all_brother.animation.block.playing
tag @s remove zelda_oot.know_it_all_brother.animation.idle_rock.playing
tag @s remove zelda_oot.know_it_all_brother.animation.idle_grass.playing
tag @s remove zelda_oot.know_it_all_brother.animation.idle_attack.playing