# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(head) run function zelda_oot:link/variants/default/zzz/apply_to_node_head
$execute as $(body) run function zelda_oot:link/variants/default/zzz/apply_to_node_body
$execute as $(left_arm) run function zelda_oot:link/variants/default/zzz/apply_to_node_left_arm
$execute as $(right_arm) run function zelda_oot:link/variants/default/zzz/apply_to_node_right_arm
$execute as $(left_leg) run function zelda_oot:link/variants/default/zzz/apply_to_node_left_leg
$execute as $(right_leg) run function zelda_oot:link/variants/default/zzz/apply_to_node_right_leg
$execute as $(ocarina) run function zelda_oot:link/variants/default/zzz/apply_to_node_ocarina
$execute as $(music) run function zelda_oot:link/variants/default/zzz/apply_to_node_music