# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(head)
$kill $(body)
$kill $(left_arm)
$kill $(right_arm)
$kill $(left_leg)
$kill $(right_leg)
$kill $(ocarina)
$kill $(music)