# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1.01f,0f,0f,0f,0f,0.9962f,0.0872f,1.4375f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9571f,0.1571f,0.2435f,0.3125f,-0.2395f,0.0444f,-0.9699f,1.3125f,-0.1632f,-0.9866f,-0.0049f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9327f,-0.3605f,-0.0075f,-0.3125f,-0.0428f,0.1314f,-0.9904f,1.3125f,0.358f,-0.9235f,-0.1379f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.965f,-0.0421f,-0.2588f,0.1188f,-0.077f,0.989f,0.1261f,0.75f,0.2507f,0.1416f,-0.9577f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9537f,0.0522f,0.2961f,-0.1187f,0.0393f,0.998f,-0.0496f,0.75f,-0.2981f,-0.0356f,-0.9539f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ocarina) {transformation: [0.9914f,0.1305f,0f,-0.7656f,-0.113f,0.8586f,0.5f,1.25f,0.0653f,-0.4957f,0.866f,0.3437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] run function zelda_oot:link/variants/blue_single_note/apply